version: '3'

services:
  tadoku-web:
    build: .
    image: tadoku/web
    container_name: tadoku-web
    network_mode: bridge
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: langlog.be
      VIRTUAL_PORT: 3000